baseurl = "https://www.d3void.net"
languageCode = "en-us"
title = "{soft,stone}ware"
theme = "hugo-tranquilpeak-theme"
googleAnalytics = "UA-96189274-1"
defaultContentLanguage = "en-us"

[author]
  name = "Scott Devoid"
  job  = "Software Engineer, Ericsson"
  location = "Cambridge, MA"
  picture = "images/avatars/devoid.png"
  twitter = "sdevoid"

[params]
  sidebarBehavior = 1
  thumbnailImage = true
  autoThumbnailImage = true
  coverImage = "/torres02_bg.jpg"

[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"

[[menu.main]]
  weight = 2
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/#about"

[[menu.links]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/devoid"
[[menu.links]]
  weight = 1
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
  url = "https://twitter.com/sdevoid"

[[menu.misc]]
  weight = 0
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"
